env:
  ANKA_MOJAVE_TEMPLATE: "10.14.4_6C_14G_40G"
  ANKA_TEMPLATE_TAG: "clean::cicd::git-ssh::nas::brew::buildkite-agent-3.11.2"
  CHECKSUMABLE: "scripts/agrio_build*"
  MAC_TAG: "agrio_1-8-0-rc2"
  WORKDIR: "/data/job"

steps:
  - wait

  - label: ":darwin: Ensure Mojave Anka Template Dependency Tag/Layer Exists"
    command:
      - "git clone git@github.com:AGRIO/mac-anka-fleet.git"
      - "cd mac-anka-fleet && . ./ensure_tag.bash -u 12 -r 25G -a '-n'"
    agents:
      - "queue=mac-anka-templater-fleet"
    env:
      REPO: "${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}"
      REPO_COMMIT: "${BUILDKITE_COMMIT}"
      CHECKSUMABLE: "${CHECKSUMABLE}"
      TEMPLATE: "${ANKA_MOJAVE_TEMPLATE}"
      TEMPLATE_TAG: "${ANKA_TEMPLATE_TAG}"
      TAG_COMMANDS: "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} && cd agr && git checkout ${BUILDKITE_COMMIT} && git submodule update --init --recursive && ./scripts/agrio_build.sh -y -P -f -m && cd .. && rm -rf agr" # CLONED_REPO_DIR IS REQUIRED and is where the repo is always cloned into
      PROJECT_TAG: "${MAC_TAG}"
    timeout: 320
    skip: $SKIP_MOJAVE

  - wait

  - label: ":darwin: [Darwin] Mojave Build"
    command: |
      git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} .
      git checkout ${BUILDKITE_COMMIT}
      git submodule update --init --recursive
      ./scripts/agrio_build.sh -y -P -m
      tar -pczf build.tar.gz build
      [[ -f build.tar.gz ]] && buildkite-agent artifact upload build.tar.gz || (echo '+++ :no_entry: ERROR: No build.tar.gz artifact found, or artifact upload failed!'; echo '$$ ls -la'; ls -la; exit 1)
    plugins:
      chef/anka#v0.4.4:
        no-volume: true
        workdir: $WORKDIR
        inherit-environment-vars: true
        vm-name: $ANKA_MOJAVE_TEMPLATE
        vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
        modify-cpu: 12
        modify-ram: 24
        always-pull: true
        debug: true
        wait-network: true
    agents:
      - "queue=mac-anka-large-node-fleet"
    timeout: 120
    skip: $SKIP_MOJAVE

  - label: ":aws: Amazon Linux 2 Build"
    command: |
      ./scripts/agrio_build.sh -y -P -m
      tar -pczf build.tar.gz build
      [[ ! -f build.tar.gz ]] && (echo '+++ :no_entry: ERROR: No build.tar.gz artifact found!'; echo '$$ ls -la'; ls -la; exit 1) || :
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.1.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    timeout: 120

  - label: ":centos: CentOS 7 Build"
    command: |
      ./scripts/agrio_build.sh -y -P -m
      tar -pczf build.tar.gz build
      [[ ! -f build.tar.gz ]] && (echo '+++ :no_entry: ERROR: No build.tar.gz artifact found!'; echo '$$ ls -la'; ls -la; exit 1) || :
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    timeout: 120

  - label: ":ubuntu: Ubuntu 16.04 Build"
    command: |
      ./scripts/agrio_build.sh -y -P -m
      tar -pczf build.tar.gz build
      [[ ! -f build.tar.gz ]] && (echo '+++ :no_entry: ERROR: No build.tar.gz artifact found!'; echo '$$ ls -la'; ls -la; exit 1) || :
    label: ":ubuntu: Ubuntu 16.04 Build"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    timeout: 120

  - label: ":ubuntu: Ubuntu 18.04 Build"
    command: |
      ./scripts/agrio_build.sh -y -P -m
      tar -pczf build.tar.gz build
      [[ ! -f build.tar.gz ]] && (echo '+++ :no_entry: ERROR: No build.tar.gz artifact found!'; echo '$$ ls -la'; ls -la; exit 1) || :
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths: "build.tar.gz"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    timeout: 120

  - wait

  # MacOS Mojave
  - label: ":darwin: [Darwin] Mojave Tests"
    command: |
      git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} .
      git checkout ${BUILDKITE_COMMIT}
      buildkite-agent artifact download build.tar.gz . --step ":darwin: [Darwin] Mojave Build"
      ./scripts/parallel-test.sh
    agents:
      - "queue=mac-anka-node-fleet"
    plugins:
      chef/anka#v0.4.4:
        no-volume: true
        workdir: $WORKDIR
        inherit-environment-vars: true
        bash-interactive: true
        vm-name: $ANKA_MOJAVE_TEMPLATE
        vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
        always-pull: true
        debug: true
        wait-network: true
    timeout: 120
    skip: $SKIP_MOJAVE$SKIP_TESTS

  - label: ":darwin: [Darwin] Mojave NP Tests"
    command: |
      git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} .
      git checkout ${BUILDKITE_COMMIT}
      buildkite-agent artifact download build.tar.gz . --step ":darwin: [Darwin] Mojave Build"
      ./scripts/serial-test.sh
    agents:
      - "queue=mac-anka-node-fleet"
    plugins:
      chef/anka#v0.4.4:
        no-volume: true
        workdir: $WORKDIR
        inherit-environment-vars: true
        bash-interactive: true
        vm-name: $ANKA_MOJAVE_TEMPLATE
        vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
        always-pull: true
        debug: true
        wait-network: true
    timeout: 120
    skip: $SKIP_MOJAVE

  # Amazon Linux 2
  - label: ":aws: Amazon Linux 2 Tests"
    command: |
      echo "--- :arrow_down: Downloading Build Directory"
      buildkite-agent artifact download build.tar.gz . --step ":aws: Amazon Linux 2 Build"
      ./scripts/parallel-test.sh
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60
    skip: $SKIP_TESTS

  - label: ":aws: Amazon Linux 2 NP Tests"
    command: |
      echo "--- :arrow_down: Downloading Build Directory"
      buildkite-agent artifact download build.tar.gz . --step ":aws: Amazon Linux 2 Build"
      ./scripts/serial-test.sh
    label: ":aws: Amazon Linux 2 NP Tests"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:amazonlinux2_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  # CentOS
  - label: ":centos: CentOS 7 Tests"
    command: |
      echo "--- :arrow_down: Downloading Build Directory"
      buildkite-agent artifact download build.tar.gz . --step ":centos: CentOS 7 Build"
      ./scripts/parallel-test.sh
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60
    skip: $SKIP_TESTS

  - label: ":centos: CentOS 7 NP Tests"
    command: |
      echo "--- :arrow_down: Downloading Build Directory"
      buildkite-agent artifact download build.tar.gz . --step ":centos: CentOS 7 Build"
      ./scripts/serial-test.sh
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  # Ubuntu 16.04
  - label: ":ubuntu: Ubuntu 16.04 Tests"
    command: |
      echo "--- :arrow_down: Downloading Build Directory"
      buildkite-agent artifact download build.tar.gz . --step ":ubuntu: Ubuntu 16.04 Build"
      ./scripts/parallel-test.sh
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60
    skip: $SKIP_TESTS

  - label: ":ubuntu: Ubuntu 16.04 NP Tests"
    command: |
      echo "--- :arrow_down: Downloading Build Directory"
      buildkite-agent artifact download build.tar.gz . --step ":ubuntu: Ubuntu 16.04 Build"
      ./scripts/serial-test.sh
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  # Ubuntu 18.04
  - label: ":ubuntu: Ubuntu 18.04 Tests"
    command: |
      echo "--- :arrow_down: Downloading Build Directory"
      buildkite-agent artifact download build.tar.gz . --step ":ubuntu: Ubuntu 18.04 Build"
      ./scripts/parallel-test.sh
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60
    skip: $SKIP_TESTS

  - label: ":ubuntu: Ubuntu 18.04 NP Tests"
    command: |
      echo "--- :arrow_down: Downloading Build Directory"
      buildkite-agent artifact download build.tar.gz . --step ":ubuntu: Ubuntu 18.04 Build"
      ./scripts/serial-test.sh
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    timeout: 60

  - wait: # Test Metrics
    continue_on_failure: true

  - command: |
        cd scripts/metrics
        node --max-old-space-size=4096 test-metrics.js
    label: ":bar_chart: Test Metrics"
    agents:
      queue: "automation-apps-builder-fleet"
    timeout: 10
    soft_fail: true

  - wait

  - label: ":centos: CentOS 7 Package Builder"
    command: |
      ./scripts/package-builder.sh ':centos: CentOS 7 Build'
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:centos7_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    env:
      OS: "el7"
      PKGTYPE: "rpm"
    timeout: 60

  - command: | # Ubuntu 16.04 Package Builder
      ./scripts/package-builder.sh ':ubuntu: Ubuntu 16.04 Build'
    label: ":ubuntu: Ubuntu 16.04 Package Builder"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu16_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    env:
      OS: "ubuntu-16.04"
      PKGTYPE: "deb"
    timeout: 60

  - command: | # Ubuntu 18.04 Package Builder
      ./scripts/package-builder.sh ':ubuntu: Ubuntu 18.04 Build'
    label: ":ubuntu: Ubuntu 18.04 Package Builder"
    agents:
      queue: "automation-large-builder-fleet"
    plugins:
      ecr#v1.1.4:
        login: true
        account_ids: "436617320021"
        no-include-email: true
        region: "us-west-2"
      docker#v3.2.0:
        shell: ["/bin/bash", "-i", "-e", "-c"]
        debug: true
        image: "436617320021.dkr.ecr.us-west-2.amazonaws.com/ci:ubuntu18_1-8-0-rc2"
        propagate-environment: true
        workdir: /data/job
    env:
      OS: "ubuntu-18.04"
      PKGTYPE: "deb"
    timeout: 60

  - label: ":darwin: Mojave Package Builder"
    command: |
      git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} .
      git checkout ${BUILDKITE_COMMIT}
      ./scripts/package-builder.sh ':darwin: [Darwin] Mojave Build'
    agents:
      - "queue=mac-anka-node-fleet"
    plugins:
      chef/anka#v0.4.4:
        no-volume: true
        workdir: $WORKDIR
        inherit-environment-vars: true
        bash-interactive: true
        vm-name: $ANKA_MOJAVE_TEMPLATE
        vm-registry-tag: "${ANKA_TEMPLATE_TAG}::${MAC_TAG}"
        always-pull: true
        debug: true
        wait-network: true
    timeout: 60
    skip: $SKIP_MOJAVE

  - wait

  - command: | # Brew Updater
        echo "+++ :arrow_down: Downloading brew files"
        buildkite-agent artifact download "agrio.rb" . --step ":darwin: Mojave Package Builder"
    label: ":darwin: Brew Updater"
    agents:
      queue: "automation-large-builder-fleet"
    artifact_paths:
      - "agrio.rb"
    timeout: 5
    skip: $SKIP_MOJAVE

  - command: | # Git Submodule Regression Check
        echo "+++ :git: Running Git Submodule Regression Check"
        ./scripts/submodule_check.sh
    label: "Git Submodule Regression Check"
    agents:
      queue: "automation-large-builder-fleet"
    timeout: 5
