version: "3"

services:
  nodagrd:
    image: agrio/agr:latest
    command: /opt/agrio/bin/nodagrd.sh --data-dir /opt/agrio/bin/data-dir -e --http-alias=nodagrd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: nodagrd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodagr-data-volume:/opt/agrio/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  kagrd:
    image: agrio/agr:latest
    command: /opt/agrio/bin/kagrd --wallet-dir /opt/agrio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=kagrd:8900 --http-alias=localhost:8900
    hostname: kagrd
    links:
      - nodagrd
    volumes:
      - kagrd-data-volume:/opt/agrio/bin/data-dir
    stop_grace_period: 10m

volumes:
 nodagr-data-volume:
   external: true
 kagrd-data-volume:
   external: true
